# Generated by Django 3.0.6 on 2020-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
