# Generated by Django 3.0.6 on 2020-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200602_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='groups',
            field=models.TextField(blank=True),
        ),
    ]
