# Generated by Django 3.1.1 on 2020-10-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='evh_mitgliedsnummer',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
