# Generated by Django 3.1.1 on 2020-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_evh_mitgliedsnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='evh_mitgliedsnummer',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
