# Generated by Django 3.1.3 on 2021-06-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210328_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='parent',
        ),
    ]
