# Generated by Django 3.1.3 on 2021-06-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0010_auto_20210621_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='auth.group'),
        ),
    ]
