#!/usr/bin/python3
# coding: utf-8

import argparse

import yaml

import smtplib

from account.models import *
import evh.settings_local as config

def send_mail(vorname, nachname, email):
    username = make_username(vorname, nachname)
    token = format_token(
        config.account_link_key,
        [vorname, nachname, username, email]
    )

    sender_from = config.EMAIL_FROM
    url = config.account_url + token.decode('utf-8')

    message = f"""From: {sender_from}
To: {vorname} {nachname} <{email}>
MIME-Version: 1.0
Content-type: text/html
Subject: [EVH Account] Link zur Account-Erstellung

<p>Hallo {vorname} {nachname},</p>
<p>
Diese Mail enth&auml;lt alle n&ouml;tigen Daten um einen Account beim Ecovillage Hannover zu erstellen. Wenn du einen Account erstellen m&ouml;chtest, dann</p>
<p><a href="{url}">Klicke auf diesen Link um einen Account zu erstellen</a></p>
<p>Sollte dieser Link nicht funktionieren, so kannst du mit dem, in dieser Mail enthaltenen Code, einen Account auf der Seite des Ecovillage erzeugen. Falls dies auch nicht klappt, wende dich gerne jederzeit an uns.
</p>
<p>
URL: {config.account_url}<br/> 
Erstellungscode: {token.decode()}</p>
"""
    try:
        conn = smtplib.SMTP(config.EMAIL_HOST)
        conn.login(config.EMAIL_HOST_USER, config.EMAIL_HOST_PASSWORD)
        conn.sendmail(config.EMAIL_HOST_USER, [email], message)
        print(f"Successfully sent email to {email}")
    except smtplib.SMTPException:
        print(f"Error: unable to send email to {email}")

def main():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('Vorname')
    parser.add_argument('Nachname')
    parser.add_argument('Mail')
    args = parser.parse_args()

    send_mail(args.Vorname, args.Nachname, args.Mail)

if __name__ == '__main__':
   main()
