# Generated by Django 2.2.11 on 2020-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
