# Generated by Django 3.0.6 on 2020-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_pollcollection_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Antwort', 'verbose_name_plural': 'Antworten'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='pollcollection',
            options={'permissions': (('vote_pollcollection', 'Umfrage abstimmen'), ('analyze_pollcollection', 'Umfrage auswerten')), 'verbose_name': 'Umfrage', 'verbose_name_plural': 'Umfragen'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('RA', 'Einfachauswahl'), ('CE', 'Mehrfachauswahl'), ('TX', 'Freitext')], default='RA', max_length=2),
        ),
    ]
