# Generated by Django 3.0.6 on 2020-05-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcollection',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='pollcollection',
            name='visible_results',
        ),
    ]
