# Generated by Django 3.0.6 on 2020-05-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200518_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='show_percent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='poll.PollCollection'),
        ),
    ]
