# Generated by Django 3.0.6 on 2020-06-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200518_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('RA', 'Einfachauswahl'), ('CE', 'Mehrfachauswahl'), ('TX', 'Freitext'), ('PR', 'Priorisierung')], default='RA', max_length=2),
        ),
    ]
