# Generated by Django 3.0.6 on 2020-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20200602_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='position',
            field=models.SmallIntegerField(default=1),
        ),
    ]
