# Generated by Django 3.0.6 on 2020-06-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_poll_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['position'], 'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
    ]
