# Generated by Django 3.0.6 on 2020-06-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20200607_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position'], 'verbose_name': 'Antwort', 'verbose_name_plural': 'Antworten'},
        ),
    ]
