# Generated by Django 3.0.6 on 2020-06-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20200607_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Antwort', 'verbose_name_plural': 'Antworten'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
    ]
