# Generated by Django 3.0.6 on 2020-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20200723_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
