# Generated by Django 3.1 on 2020-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20200723_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='export_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
