# Generated by Django 3.1 on 2020-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_item_export_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='export_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
