# Generated by Django 3.1.1 on 2020-10-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20200902_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('RA', 'Einfachauswahl'), ('CE', 'Mehrfachauswahl'), ('TX', 'Freitext'), ('PR', 'Priorisierung'), ('Y3', 'Ja-Nein-Enthaltung')], default='RA', max_length=2),
        ),
    ]
