# Generated by Django 3.1.1 on 2020-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_auto_20201008_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
