# Generated by Django 3.1.3 on 2021-03-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_item_max_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='max_votes',
            field=models.SmallIntegerField(blank=True, default=-1, null=True),
        ),
    ]
