# Generated by Django 3.2.9 on 2022-01-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_poll_max_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='export_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
